# Generated by Django 5.2.3 on 2025-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfee',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentfee',
            name='verification_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
