# Generated by Django 5.2.3 on 2025-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='visitor_id',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
