# Generated by Django 5.2.3 on 2025-07-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_paymentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
    ]
