# Generated by Django 5.2.3 on 2025-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_paymentstatus_user_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
