# Generated by Django 5.2.3 on 2025-07-03 04:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_address_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gurdian_nid',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gurdian_phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[core.validators.phone_validator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
