# Generated by Django 5.2.3 on 2025-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_blood_group_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
