# Generated by Django 5.2.3 on 2025-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gurdian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
