# Generated by Django 5.2.3 on 2025-07-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_gurdian_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
