# Generated by Django 5.2.3 on 2025-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='occupation',
            new_name='father_name_bn',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='name_bn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_en',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spouse_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spouse_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
