# Generated by Django 5.2.3 on 2025-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_account_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Draft', max_length=10),
        ),
    ]
