# Generated by Django 5.2.3 on 2025-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sub_account_status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
