# Generated by Django 5.2.3 on 2025-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_sub_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sub_account_status',
        ),
        migrations.AddField(
            model_name='user',
            name='sub_account_status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
