# Generated by Django 5.2.3 on 2025-07-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_sub_account_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gurdian_nid',
            new_name='guardian_nid',
        ),
    ]
