# Generated by Django 5.2.3 on 2025-07-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation_bn',
        ),
    ]
