# Generated by Django 5.2.3 on 2025-07-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_occupation_bn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='occupation_en',
            new_name='occupation',
        ),
    ]
