# Generated by Django 5.2.3 on 2025-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_approved_user_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
