# Generated by Django 5.2.3 on 2025-07-22 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_approved_at_user_rejected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rejectedBy',
        ),
        migrations.AddField(
            model_name='user',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
