# Generated by Django 5.2.3 on 2025-07-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_main_email',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_main_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), models.Q(('email__isnull', True), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_main_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), models.Q(('phone__isnull', True), _negated=True), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_main_phone'),
        ),
    ]
