# Generated by Django 5.2.3 on 2025-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_rejectedby_user_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
