# Generated by Django 5.2.3 on 2025-07-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='reports.reportdepartment'),
        ),
    ]
