# Generated by Django 5.2.3 on 2025-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportdepartment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdepartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
