# Generated by Django 5.2.3 on 2025-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportdepartment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
