# Generated by Django 5.2.3 on 2025-07-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
    ]
