# Generated by Django 5.2.3 on 2025-07-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='address.upazila')),
            ],
            options={
                'unique_together': {('name', 'upazila')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='address.union')),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paras', to='address.village')),
            ],
        ),
        migrations.CreateModel(
            name='Zilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zillas', to='address.division')),
            ],
            options={
                'unique_together': {('name', 'division')},
            },
        ),
        migrations.AddField(
            model_name='upazila',
            name='zilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='address.zilla'),
        ),
        migrations.AlterUniqueTogether(
            name='upazila',
            unique_together={('name', 'zilla')},
        ),
    ]
