# Generated by Django 5.2.3 on 2025-07-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='address.union')),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paras', to='address.village')),
            ],
        ),
    ]
