# Generated by Django 5.2.3 on 2025-07-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_offices', to='address.union')),
            ],
            options={
                'unique_together': {('name', 'union')},
            },
        ),
    ]
