# Generated by Django 5.2.3 on 2025-07-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_postoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.division')),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.para')),
                ('post_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.postoffice')),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.union')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.upazila')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.village')),
                ('zilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.zilla')),
            ],
        ),
    ]
